### ISSUE TITLE
During call we cannot text to other person 

### ISSUE THREAD

**Issue by pruthvirajkoppa** [nextcloud/talk-desktop#721] opened 2024-07-19 06:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead (🖼️ screenshots often help)

## Desktop client

**Talk Desktop client version:** v1.0.0

**Operating system:** Windows / MacOS / Ubuntu

**Operating system version:** Windows 11 / (In case of Linux, provide the distribution.)

**Microphone available:** yes/no

**Camera available:** yes/no

## Server

**Nextcloud version:** (see status page: `/status.php`)

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by nickvergessen** [comment] 2024-07-19 07:39
Duplicate of https://github.com/nextcloud/talk-desktop/issues/104

**Closed by nickvergessen** 2024-07-19 07:39 UTC
Labels: bug, 0. Needs triage
