### ISSUE TITLE
Boot Startup on Ubuntu 22.10

### ISSUE THREAD

**Issue by l4b4r4b4b4** [nextcloud/talk-desktop#99] opened 2023-03-28 07:06 UTC
## Steps to reproduce

1. Install Nextcloud Talk Desktop App on Ubuntu 22.10.
2. Add the app to startup programs.
3. Restart the system.

## Expected behaviour

Nextcloud Talk Desktop App should start automatically upon system startup.
## Actual behaviour

Nextcloud Talk Desktop App does not start upon system startup unless the folder name and the name of the executable are changed.

Interestingly enough, it does work, when taking the spaces out of the folders and executables name.
Desktop client

Talk Desktop client version: v1.0.0

Operating system: Ubuntu

Operating system version: 22.10

Microphone available: yes

Camera available: yes
## Server

Nextcloud version: 26.0.0

Talk app version: v0.2.2

**Comment by ShGKme** [comment] 2023-03-28 15:03
Related: #29

**Comment by nickvergessen** [comment] 2024-09-24 12:35
Duplicate of #29

**Closed by nickvergessen** 2024-09-24 12:35 UTC
Labels: bug, 1. to develop
