### ISSUE TITLE
Mac ARM64 package does not start

### ISSUE THREAD

**Issue by DrZoidberg09** [nextcloud/talk-desktop#152] opened 2023-04-16 09:27 UTC
Setup: M1 Macbook Air Ventura 13.2.1

When downloading and opening the binary, the following message appears: "Nextcloud Talk is damaged and cannot be opened..."

So far did not find a solution. Seems to be a bug when building the releases?

**Comment by ShGKme** [comment] 2023-04-16 15:28
I can confirm that **macOS arm64** package is broken. Seems, it should be built on macOS. For now, I removed **darwin-arm64** asset from the releases page thus **darwin.x64** package should work on M1 in the combability mode.

Does **darwin.x64** work on your machine?

**Comment by Gymnae** [comment] 2023-04-22 11:34
Are there plans to release ARM64 builds again, even in this early stage?

**Comment by nickvergessen** [comment] 2023-04-22 12:00
We first need a Mac device.

**Comment by Gymnae** [comment] 2023-04-22 17:29
> We first need a Mac device.

While I could help out with compiling, that won't be a real solution. Instead of buying a Mac, you could also look at the AWS offering: https://aws.amazon.com/ec2/instance-types/mac/ – it incurs costs, but could be a suitable option for building releases.

**Comment by Gymnae** [comment] 2023-07-03 11:50
Any news on this? Not having an ARM Mac could be circumvented with my comment above

**Comment by ShGKme** [comment] 2023-07-04 06:20
I'm not sure AWS still has `mac2.metal` option available. I have found a request for `mac1.metal` (intel) instance, but not `mac2` family. Scaleway also has out-of-stock for Apple M1 instances.

I'll look into GitHub Action later to check if it is suitable as a simple solution for preview. But it is not a priority for preview.

**Comment by BJKle** [comment] 2023-09-08 07:39
Hi, I know it's just a "preview version", but a good one. Since Apple doesn't sell Intel Desktop/Notebook Computers anymore, the silicon variant should be on the list as well. Please take this into consideration.
Thank you for all your efforts.

**Comment by BJKle** [comment] 2023-11-10 08:23
> Finally, GitHub has M1 actions runners 🎉
> 
> I'll look on it later
> 
> https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

Any news on an Apple Silicon version?

**Comment by BJKle** [comment] 2024-06-05 21:08
Today I took the time and build an Apple Silicon version by myself withe the given instructions. 
I replaced the black menu icon with a white image. Started it. 
Wow. It’s fast and blends well into the other menu items.

**Comment by ShGKme** [comment] 2024-11-12 16:29
> I want to mention that v1.0.0-rc.1 - Talk v20.0.2 has a darwin ARM build that says about the same "not verified/damaged".
> Testing on macOS Sequoia (15.0.1) with MacBook Air M1 (2020)

Yes, this is known, signing setup is in process.

> Is v1.0.0-beta.1 supposed to come after this rc or later? I'm surprised to see a rc before beta only.

No, there are no beta versions. Unlike server which has a huge public API, many components, and community party apps, Talk Desktop is a single application. Will have several rc and then 1.0.0 version

**Comment by OskyEdz** [comment] 2024-11-12 16:35
> No, there are no beta versions. 

It seemed like this issue had a plan to be fixed in a "beta". That's why I asked 🙂

**Comment by ShGKme** [comment] 2024-11-15 10:38
ARM support is fixed since `1.0.0-rc.1`:
- Initially with a separated ARM package on 2024-11-14 
- Replaced with `universal` signed package on 2024-11-14 

Untrusted app issue ("Nextcloud Talk is damaged and cannot be opened") is fixed by the replaced package

**Closed by ShGKme** 2024-11-15 10:38 UTC
Labels: bug, 1. to develop, os: Mac 🍎
