### ISSUE TITLE
Cannot show deck icon in Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by NangeGao** [nextcloud/talk-desktop#186] opened 2023-05-17 06:26 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead (🖼️ screenshots often help)

## Desktop client

**Talk Desktop client version:** 
Nextcloud Talk Desktop version 0.5.0
Built with Nextcloud Talk version 17.0.0-beta.3

**Operating system:** Ubuntu

**Operating system version:** Ubuntu 20.04.5 LTS

**Microphone available:** yes/no

**Camera available:** yes/no

## Server

**Nextcloud version:** 26.0.1.1

**Talk app version:** 16.0.3

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

![image](https://github.com/nextcloud/talk-desktop/assets/6187897/6b616ab3-1fe2-4ad6-828f-fd0876e56180)

**Comment by nickvergessen** [comment] 2023-05-17 06:45
Duplicate of https://github.com/nextcloud/talk-desktop/issues/53

**Closed by nickvergessen** 2023-05-17 06:45 UTC
Labels: bug, 0. Needs triage
