### ISSUE TITLE
feat: link to Talk message - open in Talk Desktop, not browser

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/talk-desktop#434] opened 2023-11-29 19:31 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
In Talk, you can link to a specific message. 
That link is in the form `https://example.com/index.php/call/1234567890#message_1234567`

In Talk Desktop currently, if a link to a specific message is shared, then clicked - it opens a new browser window to view the message.

**Describe the solution you'd like**
This message link should, when clicked, open the message in Talk Desktop, not a new browser window.

**Describe alternatives you've considered**
...

**Additional context**
You can get a message link by: clicking `...` context menu of a message, then `Copy message link`

**Comment by gerbrent** [comment] 2023-11-29 19:50
This... is a similar behaviour to in-browser Talk - it too opens a Talk message link in a new window. 
So, may be a Talk issue.
However feels like with Talk Desktop having the user leave the desktop application is more jarring from a UX perspective.

**Comment by nickvergessen** [comment] 2023-11-30 11:13
Yeah, duplicate of the following issues:

* https://github.com/nextcloud/spreed/issues/8855
* https://github.com/nextcloud/spreed/issues/10565

**Closed by nickvergessen** 2023-11-30 11:13 UTC
Labels: enhancement, 0. Needs triage
