### ISSUE TITLE
Not getting Notififaction on other device while desktop app is minimized

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-desktop#159] opened 2023-04-20 19:01 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Is there a way to have notification show up on other devices while having this app launched and minimized ?

So for example I send a message to user 1, then i minimize this app on my laptop now user 1 send me a message i dont get a notification on my mobile devices

**Comment by jgerken** [comment] 2023-05-02 11:35
Would also be nice to get notifications on the computer in that case (which I don't get). Additionally, in my opinion, notification should always be sent out as soon as the Talk app no longer is the active application as it could be in the background on a different screen etc.

**Comment by nickvergessen** [comment] 2023-05-02 11:42
Duplicate of https://github.com/nextcloud/spreed/issues/1575

And we will look into it in the nearer future

**Closed by nickvergessen** 2023-05-02 11:42 UTC
Labels: enhancement, 0. Needs triage
