### ISSUE TITLE
should desktop notifications be currently working?

### ISSUE THREAD

**Issue by wizdude** [nextcloud/talk-desktop#151] opened 2023-04-16 06:37 UTC
greetings,

i was unsure what the status of desktop notifications was, and thus whether it's just not implemented or whether there is a bug.

i searched through the issues and found commits done last month all related to notifications mentioned in issue #31 

is this still work in progress?

p.s. i am so super excited about this project. a desktop client is totally what talk was missing and I can't wait to try it out with other members in my team once it's a bit further developed. thanks so much for everyone who is working on this project 😃

**Comment by ShGKme** [comment] 2023-04-16 15:36
Hello wizdude,

Notifications should work. If you have a problem with notifications, please, provide more info:
- Versions you use
- Steps to reproduce

P.S. Please, do not remove the bag report template, especially the part with

```html
<!--- Please keep this note for other contributors -->
```

**Comment by wizdude** [comment] 2023-04-16 23:35
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---


## Steps to reproduce
1. launch talk desktop
2. setup a direct conversation between myself and another user
3. minimise talk desktop
4. send a message from the other user to myself

### Expected behaviour
I was expecting a notification of some kind

### Actual behaviour
nothing. if i maximise talk desktop, there is an indicator next to the chat advising me of unread
messages and the messages are there in the chat as expected.

## Desktop client

**Talk Desktop client version:** v0.3.1

**Operating system:** Windows

**Operating system version:** Windows 11

**Microphone available:** no

**Camera available:** no

## Server

**Nextcloud version:** (see status page: `/status.php`)
26.0.0.11

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
16.0.2

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
yes - running version dd37df185e90a42bccfcff72b3e0a7f68aadd5b6 
but this issue also occurred prior to any setup of the high-performance backend

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
yes - but this issue also occurred prior to any setup of turn

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
no

## Logs

no errors appear in the nextcloud log file.

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by nickvergessen** [comment] 2023-04-17 04:54
Duplicate of https://github.com/nextcloud/spreed/issues/1575

We are aware of it and will look into it soon

**Comment by nickvergessen** [comment] 2023-04-18 07:33
That is also what we should do in the browser. The problem is that the backend needs to know whether or not you are active/passive and that should not bombard the server with on/off requests when you toggle between 2 windows all the time.

**Comment by nickvergessen** [comment] 2023-04-19 07:16
> Isn't it possible to push notifications directly from talk desktop at all times unless focus is on the specific chat where this is occurring?

The server currently ignores participants that have an active session.
Also the frontend code of the desktop client is the same as the browser, so that is all the same thing.

Please be patient, we will fix this properly in an upcoming release.
And be assured we suffer from this as well multiple times per day, so we know about the annoyance it has currently.

**Comment by wizdude** [comment] 2023-04-19 07:19
if i take the output from what you provided above and put it into jsonlint i get the following result:

```
Error: Parse error on line 57:
...redacted)"		}	]} {	"host": "192.168.
--------------------^
Expecting 'EOF', '}', ',', ']', got '{'
```

**Comment by wizdude** [comment] 2023-04-19 07:22
> Please be patient, we will fix this properly in an upcoming release.
> And be assured we suffer from this as well multiple times per day, so we know about the annoyance it has currently.

many thanks. i'm so excited to see talk-desktop available as it really was the missing piece for many people and the only thing that's broken are the notifications. i'll be so happy when this is working 😃. 

many thanks again.

**Comment by kenke7** [comment] 2024-06-06 07:30
Any updates on this? I'm using v0.29.0 on Mac and notification still doesn't work. It affects the usability quite a lot and I think we should fix this ASAP?

**Comment by MohammedNoureldin** [comment] 2024-06-27 20:59
I also use the latest version on Windows 10, the notifications do not work or work 1% of the times, which makes them unfortunately unreliable at all.

It would be great if this can be planned soon. Thanks!

**Comment by nickvergessen** [comment] 2024-06-27 21:57
The thing I mentioned in https://github.com/nextcloud/talk-desktop/issues/151#issuecomment-1514244167 is merged long time.
Also I just received a notification on Windows 10, so that is all working with Nextcloud 29, Talk 19.0.3 and Desktop 0.31.0

**Comment by nickvergessen** [comment] 2024-06-27 21:59
On some systems there are still issues, all others should work and do work quite reliable:
- https://github.com/nextcloud/talk-desktop/issues/699
- https://github.com/nextcloud/talk-desktop/issues/641

**Closed by nickvergessen** 2024-06-27 21:59 UTC
Labels: bug

**Comment by numpa** [comment] 2024-09-04 11:08
Notifications still doesn't work on Win10 with latest Nextcloud and client app / web interface. Still completely unreliable. Sometimes notifications appear, but in 99% they don't. And no sound at all. Mobile Talk for Android works perfect.

**Comment by RTechSn** [comment] 2024-10-03 11:43
@numpa Could you please check if #822 affects you?
