### ISSUE TITLE
provide Appimage packages for Linux

### ISSUE THREAD

**Issue by mokkin** [nextcloud/talk-desktop#154] opened 2023-04-16 16:21 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Downloading, extracting and placing in the right place for the tool is quite "complicated". Therefore please try to package the App for Linux in an Appimage package, just as you do fo the desktop app or the CODE server app for instance.

**Describe the solution you'd like**
Just download Appimages (including update path)

**Describe alternatives you've considered**
Alternatively you could provide deb, yum, snap, flatpak and other packages, but this might be more time consuming as they don't conver all distributions.

**Comment by nickvergessen** [comment] 2023-04-16 16:50
We will do this once the product is more production ready.
For now those are developer or early user feedback previews and for that case the tarballs are enough.

**Comment by ChrisLauinger77** [comment] 2023-06-10 09:43
> We will do this once the product is more production ready. For now those are developer or early user feedback previews and for that case the tarballs are enough.

Looking forward to it - I would root for flatpak (as alternative to appimage which is fine too)

**Comment by Martinligabue** [comment] 2023-06-16 12:18
> as alternative to appimage

It would be better to have both flatpak and appimage, maybe even snap, so it's easier to install on any system without having to package it for each distro.

**Comment by RTechSn** [comment] 2023-12-15 12:19
Please, don't forget the .msi

**Comment by nickvergessen** [comment] 2023-12-15 14:29
Duplicate of https://github.com/nextcloud/talk-desktop/issues/257

**Closed by nickvergessen** 2023-12-15 14:29 UTC
Labels: enhancement, 1. to develop, os: Linux 🐧
