### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by ricardodfg** [nextcloud/talk-desktop#880] opened 2024-11-12 16:03 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead (🖼️ screenshots often help)
![Image](https://github.com/user-attachments/assets/347da888-8535-403b-a489-d7626826e1c0)

## Desktop client

**Talk Desktop client version:** v1.0.0-rc.1

**Operating system:** Windows 

**Operating system version:** Windows 11 

**Microphone available:** no

**Camera available:** no

## Server

**Nextcloud version:** (see status page: `/status.php`)
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"30.0.2.2","versionstring":"30.0.2","edition":"","productname":"Nextcloud","extendedSupport":false}
**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by nickvergessen** [comment] 2024-11-12 16:23
Thanks for testing, however this is a duplicate 🙈
Duplicate of #878

**Closed by nickvergessen** 2024-11-12 16:23 UTC
Labels: bug, 0. Needs triage

**Comment by ShGKme** [comment] 2024-11-12 20:38
@ricardodfg Does it happen for you at a random moment?
Or like in https://github.com/nextcloud/talk-desktop/issues/878 - on system theme change?
