### ISSUE TITLE
Mac OS: "Start call" not working (cam and mic not accessible)

### ISSUE THREAD

**Issue by marcotrevisan** [nextcloud/talk-desktop#360] opened 2023-09-23 07:24 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
I think this problem may be related to the status of the app for Mac OS (not verified).
The app is not showing up in "privacy and security" settings, in the relevant microphone and camera sections where the user can choose to allow/not allow access for the installed apps.

## Steps to reproduce

1. Open an existing chat
2. Hit the "Start call" button

### Expected behaviour
It should work like in the browser.

### Actual behaviour
Cam and microphone are unaccessible.

## Desktop client

**Talk Desktop client version:** v0.11.0 (0.11.0)

**Operating system:** MacOS (Apple Silicon M1)

**Operating system version:** Ventura 

**Microphone available:** yes

**Camera available:** yes

## Server

**Nextcloud version:** 27.0.1

**Talk app version:** 17.1

**Custom Signaling server configured:** no

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by nickvergessen** [comment] 2023-09-25 10:52
Duplicate of https://github.com/nextcloud/talk-desktop/issues/50

**Closed by nickvergessen** 2023-09-25 10:52 UTC
Labels: bug, 0. Needs triage
